version: 2.0.0+{build}
image: Visual Studio 2019
pull_requests:
  do_not_increment_build_number: false
branches:
  only:
  - master
before_build:
- nuget restore
build:
  verbosity: minimal
  publish_nuget: true
  publish_nuget_symbols: false

